spring:
server:
  port: 8090
  address: 0.0.0.0
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL ?? ??? Table???? ??
      sqlonly: INFO
      sqltiming: WARN
      connection : OFF
      log4jdbc.log4j2: ERROR